
#Postgresql Config
spring.datasource.url=jdbc:postgresql://dpg-d770g5gule4c7397sls0-a.singapore-postgres.render.com/moneymanager_rtk8
spring.datasource.username=moneymanager_rtk8_user
spring.datasource.password=DYxUTAD5Zp9jsKPNg88IeKhjKudy3NKb

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vickykumar09012003@gmail.com
spring.mail.password=rify rdhg njnr aryg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=tr@gmail.com